version: '3'

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    networks:
      - NT
    volumes:
      - DB:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    networks:
      - NT
    volumes:
      - WordPress:/var/www/html
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    networks:
      - NT
    ports:
      - 443:443
    volumes:
      - WordPress:/var/www/html
networks:
  NT:

volumes:
  WordPress:
    external: true
  DB: